on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: Actions/checkout@v3 
        
      - name: 'login to dockerHub'
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }} 
      
      - name: "build docker images"
        run: docker build -t ${{ secrets.USERNAME }}/myimage .
      
      - name: "push docker images"
        run: docker push ${{ secrets.USERNAME }}/myimage